apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-knative-demo-deployment
spec:
  selector:
    matchLabels:
      app: springboot-knative-demo
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8096"
      labels:
        app: springboot-knative-demo
    spec:
      containers:
      - name: springboot-knative-demo
        image: dockertestbaby/springboot-knative-demo
        ports:
        - containerPort: 8096
        env:
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mongodb
                key: database-name
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: database-password
        readinessProbe:
          httpGet:
            port: 8096
            path: /readiness
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-knative-demo-service
spec:
  type: NodePort
  selector:
    app: springboot-knative-demo
  ports:
  - port: 8096
